from fastapi import FastAPI, UploadFile
from uuid import uuid4
from .utils.file import save_to_disk
from .db.collections.files import files_collection, FileSchema

app = FastAPI()

@app.get("/")
def hello():
    return {"status": "container is healthy and fit"}

@app.post("/upload")
async def upload_file(file: UploadFile):

    # id = uuid4()
    # user upload file before saving into disk save status in db as saving
    db_file = await files_collection.insert_one(
        document = FileSchema(
            name = file.filename,
            status = 'saving'
        )
    )


    # determine the path for the file user upload using id generated by mongodb
    file_path = f"/mnt/uploads/{str(db_file.inserted_id)}/{file.filename}"

    # saving into disk
    await save_to_disk(file = await file.read() , path = file_path)

    #pushed to queue
    print("pushing file in queue")

    #updating status in mongodb
    await files_collection.update_one(
        {"_id": db_file.inserted_id},
        {
            "$set":{
                "status":"queued"
            }
        }
    )


    return {"file_id": str(db_file.inserted_id)}


